#!/bin/bash
### BEGIN INIT INFO
# Provides: clean-env
# Required-Start: $local_fs
# Required-Stop: $local_fs
# Default-Start: 5
# Default-Stop: 0 6
# Short-Description: Commands for user home directory
# Description: Operations before shutdown/reboot
### END INIT INFO

# symlinks:
# rc5.d/S00clean-env
# rc6.d/K00clean-env

case "$1" in
	stop)
		dotfiles=(.bash_history .gdb_history .lesshst .tig_history .viminfo .wget-hsts)
		main_user=/home/`getent passwd 1000 | cut -d ':' -f1`

		for f in ${dotfiles[*]}; do
			for u in /root $main_user; do
				if [ -e "$u/$f" ]; then
					shred -uzn 0 "$u/$f"
				fi
			done
		done

		if [ -d $main_user/.ssh ]; then
			chmod 700 $main_user/.ssh
			chmod 600 $main_user/.ssh/*
		fi

		exit 0
	;;
esac
